### ISSUE TITLE
[BUG] Editting flashcards immediately shifts to the next card

### ISSUE THREAD

**Issue by richardrl** [st3v3nmw/obsidian-spaced-repetition#630]
**Describe the bug**
<img width="44" alt="image" src="https://user-images.githubusercontent.com/5181990/219578729-6ac7c273-3e6b-4776-8215-34b5d5675704.png">
If I click on the above button, it immediately shifts to the next card. I have no idea if it is considered red, blue, or green difficulty - I'm not even sure what happens or why it shifts. The expected behavior after an edit is to remain on the card and wait for a red,blue or green button press, on?

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain the bug. This could be the logs in the developer console (`CTRL` + `SHIFT` + `i`).

**Versions (please complete the following information):**

-   OS: [e.g. iOS] Ubuntu
-   Obsidian version: [e.g. v0.12.4] Latest as of current date
-   Plugin version: [e.g. v1.4.9] Latest as of current date
-   If on desktop, Installer version: [run `this.navigator.appVersion` on the developer console, e.g. `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"`]

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by maggaou** [comment]
I can confirm that this happens sometimes. I think it can be hard to reproduce because it doesn't happen always.

**Comment by AB1908** [comment]
This is painful if it doesn't always happen. That said, I was the one who designed it this way. The intention is that if you're editing a card, you know what the answer immediately is and thus can't really test yourself, so I set it to auto skip. The exact line is https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/274da1b7f993a7e56043b51fae4ee8f53dd80689/src/flashcard-modal.tsx#L413.

**Comment by richardrl** [comment]
> This is painful if it doesn't always happen. That said, I was the one who designed it this way. The intention is that if you're editing a card, you know what the answer immediately is and thus can't really test yourself, so I set it to auto skip. The exact line is
> 
> https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/274da1b7f993a7e56043b51fae4ee8f53dd80689/src/flashcard-modal.tsx#L413
> 
> . It does not skip if you haven't edited the answer since there's a chance someone clicked it accidentally, made no changes and submitted and still want to test themselves on the card.

Many, many times I edit an answer because I want to improve how the card is written. But I still want to test myself on it, or update the mastery. I think it would make more sense to not skip. If the user wants to skip the skip button is also available.

**Comment by AB1908** [comment]
Feel free to submit a PR that removes this line. Should fix it.

**Comment by richardrl** [comment]
@AB1908 can you approve the PR? 

Also, does it automatically get published to the Obsidian store after it is merged to master?

**Comment by AB1908** [comment]
I can't approve it, the author is the only one with permissions but thanks for taking care of that!

**Comment by richardrl** [comment]
@AB1908 So the change was been pushed. However, I would expect after editting and saving, the card would be refreshed with the new version (but still not skipping to the next card) but that doesn't happen now. Do you know how to fix this?

**Comment by AB1908** [comment]
That's probably a little harder. I can't speak to it unfortunately as I'm very out of touch with the codebase.

**Comment by richardrl** [comment]
@st3v3nmw Hi Steven, would you know how to change this?

**Comment by st3v3nmw** [comment]
Hi @richardrl,
Yes, it's possible. We'll be tracking the new issue in #686.
I'm closing this issue since we're no longer shifting to the next card after editing
